using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyBullet : MonoBehaviour
{
    void Update()
    {
        Invoke("DelayDestroy", 10.0f);
    }

    public void OnCollisionEnter(Collision collision)
    {
        // ƒvƒŒƒCƒ„[‚ÉÕ“Ë‚µ‚½‚É’e‚ğíœ‚·‚é
        if (collision.gameObject.CompareTag("Player"))
        {
            Destroy(this.gameObject);
        }

        // ’e‚ğÁ‚·•Ç‚ÉÕ“Ë‚µ‚½‚É’e‚ğíœ‚·‚é
        if (collision.gameObject.CompareTag("Object Wall"))
        {
            Destroy(this.gameObject);
        }
    }

    private void DelayDestroy()
    {
        Destroy(this.gameObject);
    }
}
